# A workflow to build and push a Docker image to Amazon ECR
name: Build and push image to ECR

on:
  push:
    branches: ["main"]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image   
        run: |
         docker build -t ${{ secrets.ECR_REPOSITORY }}/:${{ GITHUB_RUN_NUMBER }} .
         docker tag ${{ secrets.ECR_REPOSITORY }}:${{ GITHUB_RUN_NUMBER }} ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:${{ GITHUB_RUN_NUMBER}}

      - name: Push Docker image to ECR
        run: |
         docker push ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:${{ GITHUB_RUN_NUMBER}}
